package com.cg.exceptiontest;

import org.junit.jupiter.api.Test;

import com.cg.exception.ApiError;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

class ApiErrorTest {

    @Test
    void constructor_shouldSetAllFieldsCorrectly() {

        ApiError error = new ApiError(
                404,
                "NOT_FOUND",
                "Resource not found",
                "/products/1"
        );

        assertEquals(404, error.getStatus());
        assertEquals("NOT_FOUND", error.getError());
        assertEquals("Resource not found", error.getMessage());
        assertEquals("/products/1", error.getPath());
        assertNotNull(error.getTimestamp());
    }

    @Test
    void timestamp_shouldBeAutoGenerated() {

        ApiError error = new ApiError(
                500,
                "INTERNAL_SERVER_ERROR",
                "Something went wrong",
                "/dashboard"
        );

        assertTrue(error.getTimestamp().isBefore(LocalDateTime.now().plusSeconds(1)));
    }

    @Test
    void fields_shouldNotBeNull_whenProperlyConstructed() {

        ApiError error = new ApiError(
                400,
                "BAD_REQUEST",
                "Invalid input",
                "/customers"
        );

        assertNotNull(error.getStatus());
        assertNotNull(error.getError());
        assertNotNull(error.getMessage());
        assertNotNull(error.getPath());
        assertNotNull(error.getTimestamp());
    }
}